/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { PhotographyServiceCategory, PhotographyServiceItem } from '../features/photography-service/types';

export const PHOTOGRAPHY_SERVICE_CATEGORIES: PhotographyServiceCategory[] = [
    { id: 'idphoto', labelKey: 'service.category.idphoto', order: 1 },
    { id: 'corporate', labelKey: 'service.category.corporate', order: 2 },
    { id: 'portrait', labelKey: 'service.category.portrait', order: 3 },
    { id: 'themed', labelKey: 'service.category.themed', order: 4 },
    { id: 'couple', labelKey: 'service.category.couple', order: 5 },
    { id: 'group', labelKey: 'service.category.group', order: 6 },
];

export const PHOTOGRAPHY_SERVICE_ITEMS: PhotographyServiceItem[] = [
    // --- ID Photo ---
    {
        id: 'id-photo-self',
        categoryId: 'idphoto',
        nameKey: 'service.item.id_photo_self.name',
        descriptionKey: 'service.item.id_photo_self.desc',
        priceRange: 'NT$ 590',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/idphoto?level=self',
    },
    {
        id: 'id-photo-natural',
        categoryId: 'idphoto',
        nameKey: 'service.item.id_photo_natural.name',
        descriptionKey: 'service.item.id_photo_natural.desc',
        priceRange: 'NT$ 890',
        badgeKey: 'service.badge.popular',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/idphoto?level=standard',
    },
    {
        id: 'id-photo-premium',
        categoryId: 'idphoto',
        nameKey: 'service.item.id_photo_premium.name',
        descriptionKey: 'service.item.id_photo_premium.desc',
        originalPrice: 'NT$ 1,500',
        priceRange: 'NT$ 1,290',
        badgeKey: 'service.badge.popular',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/idphoto?level=premium',
    },

    // --- Corporate (Professional Portrait) ---
    {
        id: 'premium-leader-corp',
        categoryId: 'corporate',
        nameKey: 'service.item.premium_leader.name',
        descriptionKey: 'service.item.premium_leader.desc',
        originalPrice: 'NT$ 8,000',
        priceRange: 'NT$ 6,000',
        badgeKey: 'service.badge.limited',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/portrait?type=premium_leader',
    },
    {
        id: 'premium-erya',
        categoryId: 'corporate',
        nameKey: 'service.item.premium_erya.name',
        descriptionKey: 'service.item.premium_erya.desc',
        originalPrice: 'NT$ 8,800',
        priceRange: 'NT$ 6,600',
        badgeKey: 'service.badge.limited',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/portrait?type=premium_erya',
    },
    {
        id: 'corporate-mag',
        categoryId: 'corporate',
        nameKey: 'service.item.corporate_mag.name',
        descriptionKey: 'service.item.corporate_mag.desc',
        originalPrice: 'NT$ 7,300',
        priceRange: 'NT$ 3,800 ~ 6,300',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/portrait?type=corporate_mag',
    },
    {
        id: 'corp-grad-half',
        categoryId: 'corporate',
        nameKey: 'service.item.corp_grad_half.name',
        descriptionKey: 'service.item.corp_grad_half.desc',
        originalPrice: 'NT$ 3,200',
        priceRange: 'NT$ 2,600',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/portrait?type=graduation&spec=half_body',
    },
    {
        id: 'corp-half-1',
        categoryId: 'corporate',
        nameKey: 'service.item.portrait_business_half.name',
        descriptionKey: 'service.item.portrait_business_half.desc',
        originalPrice: 'NT$ 3,200',
        priceRange: 'NT$ 2,600',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/portrait?type=business&spec=half_body',
    },
    {
        id: 'corp-half-5',
        categoryId: 'corporate',
        nameKey: 'service.item.corp_half_5.name',
        descriptionKey: 'service.item.corp_half_5.desc',
        originalPrice: 'NT$ 6,400',
        priceRange: 'NT$ 5,200',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/portrait?type=business&spec=half_body',
    },
    {
        id: 'corp-grad-full',
        categoryId: 'corporate',
        nameKey: 'service.item.corp_grad_full.name',
        descriptionKey: 'service.item.corp_grad_full.desc',
        originalPrice: 'NT$ 4,000',
        priceRange: 'NT$ 3,000',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/portrait?type=graduation&spec=full_body',
    },
    {
        id: 'corp-full-1',
        categoryId: 'corporate',
        nameKey: 'service.item.portrait_business_full.name',
        descriptionKey: 'service.item.portrait_business_full.desc',
        originalPrice: 'NT$ 4,000',
        priceRange: 'NT$ 3,000',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/portrait?type=business&spec=full_body',
    },
    {
        id: 'corp-full-5',
        categoryId: 'corporate',
        nameKey: 'service.item.corp_full_5.name',
        descriptionKey: 'service.item.corp_full_5.desc',
        originalPrice: 'NT$ 7,200',
        priceRange: 'NT$ 6,000',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/portrait?type=business&spec=full_body',
    },
    {
        id: 'cabin-half',
        categoryId: 'corporate',
        nameKey: 'service.item.cabin_half.name',
        descriptionKey: 'service.item.cabin_half.desc',
        originalPrice: 'NT$ 4,000',
        priceRange: 'NT$ 3,200',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/portrait?type=cabin_crew&spec=half_body',
    },
    {
        id: 'cabin-full',
        categoryId: 'corporate',
        nameKey: 'service.item.cabin_full.name',
        descriptionKey: 'service.item.cabin_full.desc',
        originalPrice: 'NT$ 4,400',
        priceRange: 'NT$ 3,600',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/portrait?type=cabin_crew&spec=full_body',
    },
    {
        id: 'model-card',
        categoryId: 'corporate',
        nameKey: 'service.item.model_card.name',
        descriptionKey: 'service.item.model_card.desc',
        originalPrice: 'NT$ 4,600',
        priceRange: 'NT$ 3,200',
        badgeKey: 'service.badge.limited',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/portrait?type=model_card',
    },

    // --- Portrait ---
    {
        id: 'portrait-resume-grad',
        categoryId: 'portrait',
        nameKey: 'service.item.portrait_resume_grad.name',
        descriptionKey: 'service.item.portrait_resume_grad.desc',
        originalPrice: 'NT$ 2,400',
        priceRange: 'NT$ 2,200',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/portrait?type=portrait_resume_grad',
    },
    {
        id: 'portrait-resume',
        categoryId: 'portrait',
        nameKey: 'service.item.portrait_resume.name',
        descriptionKey: 'service.item.portrait_resume.desc',
        originalPrice: 'NT$ 2,400',
        priceRange: 'NT$ 2,200',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/portrait?type=portrait_resume',
    },

    // --- Themed ---
    {
        id: 'themed-birthday',
        categoryId: 'themed',
        nameKey: 'service.item.themed_birthday.name',
        descriptionKey: 'service.item.themed_birthday.desc',
        originalPrice: 'NT$ 4,800',
        priceRange: 'NT$ 3,800 ~ 7,900',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/themed?type=themed-birthday',
    },
    {
        id: 'themed-magazine',
        categoryId: 'themed',
        nameKey: 'service.item.themed_magazine.name',
        descriptionKey: 'service.item.themed_magazine.desc',
        originalPrice: 'NT$ 4,800',
        priceRange: 'NT$ 3,800 ~ 7,900',
        badgeKey: 'service.badge.new',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/themed?type=themed-magazine',
    },
    {
        id: 'themed-grad-polaroid',
        categoryId: 'themed',
        nameKey: 'service.item.themed_grad_polaroid.name',
        descriptionKey: 'service.item.themed_grad_polaroid.desc',
        originalPrice: 'NT$ 2,499',
        priceRange: 'NT$ 990',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/themed?type=themed-grad-polaroid',
    },
    {
        id: 'themed-polaroid',
        categoryId: 'themed',
        nameKey: 'service.item.themed_polaroid.name',
        descriptionKey: 'service.item.themed_polaroid.desc',
        originalPrice: 'NT$ 2,499',
        priceRange: 'NT$ 1,800',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/themed?type=themed-polaroid',
    },
    {
        id: 'themed-polaroid-set',
        categoryId: 'themed',
        nameKey: 'service.item.themed_polaroid_set.name',
        descriptionKey: 'service.item.themed_polaroid_set.desc',
        originalPrice: 'NT$ 4,200',
        priceRange: 'NT$ 3,800',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/themed?type=themed-polaroid-set',
    },
    {
        id: 'themed-sport',
        categoryId: 'themed',
        nameKey: 'service.item.themed_sport.name',
        descriptionKey: 'service.item.themed_sport.desc',
        originalPrice: 'NT$ 3,200',
        priceRange: 'NT$ 2,600',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/themed?type=themed-sport',
    },
    {
        id: 'themed-maternity',
        categoryId: 'themed',
        nameKey: 'service.item.themed_maternity.name',
        descriptionKey: 'service.item.themed_maternity.desc',
        originalPrice: 'NT$ 3,200',
        priceRange: 'NT$ 2,600',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/themed?type=themed-maternity',
    },
    {
        id: 'themed-kendall',
        categoryId: 'themed',
        nameKey: 'service.item.themed_kendall.name',
        descriptionKey: 'service.item.themed_kendall.desc',
        originalPrice: 'NT$ 4,200',
        priceRange: 'NT$ 3,200',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/themed?type=themed-kendall',
    },
    {
        id: 'themed-us-college',
        categoryId: 'themed',
        nameKey: 'service.item.themed_us_college.name',
        descriptionKey: 'service.item.themed_us_college.desc',
        originalPrice: 'NT$ 3,200',
        priceRange: 'NT$ 2,600',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/themed?type=themed-us-college',
    },
    {
        id: 'themed-us-sport',
        categoryId: 'themed',
        nameKey: 'service.item.themed_us_sport.name',
        descriptionKey: 'service.item.themed_us_sport.desc',
        originalPrice: 'NT$ 5,200',
        priceRange: 'NT$ 3,600',
        badgeKey: 'service.badge.limited',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/themed?type=themed-us-sport',
    },
    {
        id: 'themed-retro-high',
        categoryId: 'themed',
        nameKey: 'service.item.themed_retro_high.name',
        descriptionKey: 'service.item.themed_retro_high.desc',
        originalPrice: 'NT$ 5,200',
        priceRange: 'NT$ 3,600',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/themed?type=themed-retro-high',
    },
    {
        id: 'themed-music',
        categoryId: 'themed',
        nameKey: 'service.item.themed_music.name',
        descriptionKey: 'service.item.themed_music.desc',
        originalPrice: 'NT$ 3,200',
        priceRange: 'NT$ 2,600',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/themed?type=themed-music',
    },
    {
        id: 'themed-kids',
        categoryId: 'themed',
        nameKey: 'service.item.themed_kids.name',
        descriptionKey: 'service.item.themed_kids.desc',
        originalPrice: 'NT$ 3,200',
        priceRange: 'NT$ 2,600',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/themed?type=themed-kids',
    },
    {
        id: 'themed-pet-owner',
        categoryId: 'themed',
        nameKey: 'service.item.themed_pet_owner.name',
        descriptionKey: 'service.item.themed_pet_owner.desc',
        originalPrice: 'NT$ 5,800',
        priceRange: 'NT$ 4,200',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/themed?type=themed-pet-owner',
    },
    {
        id: 'themed-pet',
        categoryId: 'themed',
        nameKey: 'service.item.themed_pet.name',
        descriptionKey: 'service.item.themed_pet.desc',
        originalPrice: 'NT$ 3,000',
        priceRange: 'NT$ 2,200',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/themed?type=themed-pet',
    },

    // --- Couple ---
    {
        id: 'couple-romance',
        categoryId: 'couple',
        nameKey: 'service.item.couple_romance.name',
        descriptionKey: 'service.item.couple_romance.desc',
        originalPrice: 'NT$ 4,600',
        priceRange: 'NT$ 3,400',
        actionLabelKey: 'service.action.travel',
        targetRoute: '/travel',
    },
    {
        id: 'couple-bestie',
        categoryId: 'couple',
        nameKey: 'service.item.couple_bestie.name',
        descriptionKey: 'service.item.couple_bestie.desc',
        originalPrice: 'NT$ 4,600',
        priceRange: 'NT$ 3,400',
        actionLabelKey: 'service.action.travel',
        targetRoute: '/travel',
    },
    {
        id: 'couple-retro-high',
        categoryId: 'couple',
        nameKey: 'service.item.couple_retro_high.name',
        descriptionKey: 'service.item.couple_retro_high.desc',
        originalPrice: 'NT$ 5,600',
        priceRange: 'NT$ 4,600',
        actionLabelKey: 'service.action.travel',
        targetRoute: '/travel',
    },
    {
        id: 'couple-us-college',
        categoryId: 'couple',
        nameKey: 'service.item.couple_us_college.name',
        descriptionKey: 'service.item.couple_us_college.desc',
        originalPrice: 'NT$ 4,600',
        priceRange: 'NT$ 3,600',
        actionLabelKey: 'service.action.travel',
        targetRoute: '/travel',
    },
    {
        id: 'couple-office',
        categoryId: 'couple',
        nameKey: 'service.item.couple_office.name',
        descriptionKey: 'service.item.couple_office.desc',
        originalPrice: 'NT$ 4,600',
        priceRange: 'NT$ 3,600',
        actionLabelKey: 'service.action.travel',
        targetRoute: '/travel',
    },
    {
        id: 'couple-home',
        categoryId: 'couple',
        nameKey: 'service.item.couple_home.name',
        descriptionKey: 'service.item.couple_home.desc',
        originalPrice: 'NT$ 4,600',
        priceRange: 'NT$ 3,600',
        actionLabelKey: 'service.action.travel',
        targetRoute: '/travel',
    },
    {
        id: 'couple-dragon',
        categoryId: 'couple',
        nameKey: 'service.item.couple_dragon.name',
        descriptionKey: 'service.item.couple_dragon.desc',
        originalPrice: 'NT$ 8,800',
        priceRange: 'NT$ 6,600',
        actionLabelKey: 'service.action.travel',
        targetRoute: '/travel',
    },
    {
        id: 'couple-robe',
        categoryId: 'couple',
        nameKey: 'service.item.couple_robe.name',
        descriptionKey: 'service.item.couple_robe.desc',
        originalPrice: 'NT$ 4,600',
        priceRange: 'NT$ 3,600',
        actionLabelKey: 'service.action.travel',
        targetRoute: '/travel',
    },
    {
        id: 'couple-6',
        categoryId: 'couple',
        nameKey: 'service.item.couple_6.name',
        descriptionKey: 'service.item.couple_6.desc',
        originalPrice: 'NT$ 9,600',
        priceRange: 'NT$ 7,200',
        actionLabelKey: 'service.action.travel',
        targetRoute: '/travel',
    },
    {
        id: 'couple-polaroid',
        categoryId: 'couple',
        nameKey: 'service.item.promo_duo_polaroid.name',
        descriptionKey: 'service.item.promo_duo_polaroid.desc',
        originalPrice: 'NT$ 5,299',
        priceRange: 'NT$ 4,200',
        actionLabelKey: 'service.action.travel',
        targetRoute: '/travel',
    },
    {
        id: 'couple-marriage',
        categoryId: 'couple',
        nameKey: 'service.item.promo_combo_c.name',
        descriptionKey: 'service.item.promo_combo_c.desc',
        originalPrice: 'NT$ 5,000',
        priceRange: 'NT$ 3,800',
        actionLabelKey: 'service.action.generate',
        targetRoute: '/idphoto',
    },

    // --- Group ---
    {
        id: 'promo-family-spring',
        categoryId: 'group',
        nameKey: 'service.item.promo_family_spring.name',
        descriptionKey: 'service.item.promo_family_spring.desc',
        originalPrice: 'NT$ 11,299',
        priceRange: 'NT$ 4,990 - 5,990',
        badgeKey: 'service.badge.limited',
        actionLabelKey: 'service.action.view',
        targetRoute: '/travel',
    },
    {
        id: 'group-family',
        categoryId: 'group',
        nameKey: 'service.item.group_family.name',
        descriptionKey: 'service.item.group_family.desc',
        originalPrice: 'NT$ 6,000',
        priceRange: 'NT$ 4,000',
        actionLabelKey: 'service.action.travel',
        targetRoute: '/travel',
    },
    {
        id: 'group-family-6',
        categoryId: 'group',
        nameKey: 'service.item.group_family_6.name',
        descriptionKey: 'service.item.group_family_6.desc',
        originalPrice: 'NT$ 10,800',
        priceRange: 'NT$ 8,800',
        actionLabelKey: 'service.action.travel',
        targetRoute: '/travel',
    },
    {
        id: 'group-new-style',
        categoryId: 'group',
        nameKey: 'service.item.group_new_style.name',
        descriptionKey: 'service.item.group_new_style.desc',
        originalPrice: 'NT$ 6,600',
        priceRange: 'NT$ 5,000',
        badgeKey: 'service.badge.limited',
        actionLabelKey: 'service.action.travel',
        targetRoute: '/travel',
    },
    {
        id: 'group-new-style-6',
        categoryId: 'group',
        nameKey: 'service.item.group_new_style_6.name',
        descriptionKey: 'service.item.group_new_style_6.desc',
        originalPrice: 'NT$ 11,800',
        priceRange: 'NT$ 9,800',
        badgeKey: 'service.badge.limited',
        actionLabelKey: 'service.action.travel',
        targetRoute: '/travel',
    },
    {
        id: 'group-grad',
        categoryId: 'group',
        nameKey: 'service.item.group_grad.name',
        descriptionKey: 'service.item.group_grad.desc',
        originalPrice: 'NT$ 5,600',
        priceRange: 'NT$ 4,200',
        actionLabelKey: 'service.action.travel',
        targetRoute: '/travel',
    },
    {
        id: 'group-grad-6',
        categoryId: 'group',
        nameKey: 'service.item.group_grad_6.name',
        descriptionKey: 'service.item.group_grad_6.desc',
        originalPrice: 'NT$ 11,000',
        priceRange: 'NT$ 9,000',
        actionLabelKey: 'service.action.travel',
        targetRoute: '/travel',
    },
];
