/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'zh-TW';

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.title": "Pixshop",
    "common.none": "None",

    "start.title_part1": "AI-Powered Photo Editor",
    "start.title_part2": "& Generator",
    "start.subtitle": "Upload a photo to edit, or describe what you want and let AI generate it for you.",
    "start.tab_upload": "Upload Image",
    "start.tab_generate": "Generate Image",
    "start.upload_button": "Upload an Image",
    "start.upload_drag": "or drag and drop a file",
    "start.select_image": "Select an image to edit",
    "start.edit_this": "Edit This",
    "start.generate_new": "Generate New Images",
    "start.prompt_placeholder": "Describe the image you want to create (e.g., 'A futuristic city with neon lights at night')",
    "start.aspect_ratio": "Aspect Ratio",
    "start.image_count": "Image Count",
    "start.generate_button": "Generate Image",
    "start.generating": "Generating...",
    "start.generate_pro_slow_hint": "Using Gemini 3 Pro for image generation may take 1–2 minutes. Please wait.",
    "start.feature_retouch_title": "Precise Retouching",
    "start.feature_retouch_desc": "Click any point on your image to remove blemishes, change colors, or add elements with pinpoint accuracy.",
    "start.feature_filter_title": "Creative Filters",
    "start.feature_filter_desc": "Transform photos with artistic styles. From vintage looks to futuristic glows, find or create the perfect filter.",
    "start.feature_adjust_title": "Pro Adjustments",
    "start.feature_adjust_desc": "Enhance lighting, blur backgrounds, or change the mood. Get studio-quality results without complex tools.",
    "start.error_no_prompt": "Please enter a description for the image.",
    "start.error_gen_failed": "Failed to generate image.",

    "start.tab_idphoto": "ID Photo",
    "start.tab_travel": "Travel Photo",
    "start.idphoto_title": "AI ID Photo",
    "start.idphoto_upload_hint": "Upload a clear front-facing portrait",
    "start.idphoto_generate_btn": "Generate ID Photo",
    "start.idphoto_generating": "Generating ID photo...",
    "start.idphoto_download": "Download",
    "start.idphoto_again": "Generate Another",
    "start.idphoto_edit": "Edit in Editor",
    "start.idphoto_change_photo": "Change Photo",
    "start.error_no_image_idphoto": "Please upload a portrait first.",
    "start.error_idphoto_failed": "ID photo generation failed.",

    "idphoto.label.type": "Document Type",
    "idphoto.label.level": "Retouch Level",
    "idphoto.label.spec": "Output",
    "idphoto.level.premium": "Premium Professional",
    "idphoto.level.standard": "Standard Natural",
    "idphoto.level.self": "SELF No Retouching",
    "idphoto.type.domestic": "Domestic ID",
    "idphoto.type.passport": "Passport/Visa",
    "idphoto.type.taiwan_compatriot": "Taiwan Travel Permit",
    "idphoto.type.student": "Student ID",
    "idphoto.type.work": "Work ID",
    "idphoto.type.military_police_medical": "Military/Police/Medical",
    "idphoto.type.cabin_crew": "Cabin Crew",
    "idphoto.type.graduation": "Graduation",
    "idphoto.spec.head_shoulders": "2\" Head & Shoulders",
    "idphoto.spec.half_body": "2\" Half Body",
    "idphoto.label.clothing": "Clothing",
    "idphoto.clothing.original": "Original (from photo)",
    "idphoto.clothing.scene_default": "Scene default",
    "idphoto.clothing.business": "Business attire",
    "idphoto.clothing.casual": "Casual / home wear",
    "idphoto.clothing.graduation_gown": "Graduation gown",
    "idphoto.clothing.suit": "Suit",
    "idphoto.clothing.custom": "Custom (enter below)",
    "idphoto.clothing.custom_placeholder": "Describe the clothing (e.g., white shirt, red tie)",
    "idphoto.clothing.custom_image_label": "Reference photo (optional)",
    "idphoto.clothing.custom_image_btn": "Choose",
    "idphoto.clothing.custom_image_remove": "Remove",
    "idphoto.error_custom_clothing_empty": "Please enter a description and/or upload a reference image.",
    "idphoto.model_recommendation": "Recommend using Gemini 3 Pro for better identity consistency. Switch in Settings.",
    "idphoto.result.params_title": "Generation parameters",

    "travel.title": "AI Travel Photo",
    "travel.upload_hint": "Upload a clear portrait (face visible)",
    "travel.change_photo": "Change Photo",
    "travel.generate_btn": "Generate Travel Photo",
    "travel.generating": "Generating travel photo...",
    "travel.result_scene_label": "Scene:",

    "travel.weather.random": "Random",
    "travel.weather.sunny": "Sunny",
    "travel.weather.rainy": "Rainy",
    "travel.weather.snowy": "Snowy",
    "travel.weather.cloudy": "Cloudy",
    "travel.weather.misty": "Misty",

    "travel.time.random": "Random",
    "travel.time.dawn": "Dawn",
    "travel.time.noon": "Noon",
    "travel.time.sunset": "Sunset",
    "travel.time.night": "Night",

    "travel.vibe.zen": "Zen",
    "travel.vibe.retro": "Retro",
    "travel.vibe.cyberpunk": "Cyberpunk",
    "travel.vibe.street": "Street",
    "travel.vibe.elegant": "Elegant",
    "travel.vibe.adventure": "Adventure",
    "travel.vibe.cozy": "Cozy",
    "travel.vibe.futuristic": "Futuristic",
    "travel.vibe.romantic": "Romantic",
    "travel.mode.single": "Single Person",
    "travel.mode.group": "Group / Couple",
    "travel.label.group_upload": "Upload Portraits (Max 4)",
    "travel.error_no_images": "Please upload at least one person's photo",
    "travel.status.group_analyzing": "Analyzing group features...",

    "travel.label.weather": "Weather",
    "travel.label.time": "Time",
    "travel.label.vibe": "Vibe Filter",
    "travel.label.vibe_desc": "Recommended based on location",
    "travel.label.outfit": "Outfit",
    "travel.label.pose": "Pose",
    "travel.label.group_subject": "Subject Settings",
    "travel.label.group_environment": "Environment Settings",
    "travel.label.group_aesthetics": "Artistic Style",

    "travel.outfit.default": "Default",
    "travel.outfit.casual": "Casual",
    "travel.outfit.formal": "Formal",
    "travel.outfit.traditional": "Traditional",
    "travel.outfit.winter": "Winter",
    "travel.outfit.summer": "Summer",
    "travel.outfit.hiking": "Hiking",
    "travel.outfit.cyberpunk": "Cyberpunk",
    "travel.outfit.luxury": "Quiet Luxury",
    "travel.outfit.vintage": "Vintage Classic",
    "travel.outfit.street_chic": "Streetwear Chic",
    "travel.outfit.preppy": "Preppy Style",
    "travel.outfit.boho": "Boho Chic",
    "travel.outfit.parisian": "Parisian Chic",
    "travel.outfit.academic": "Dark Academia",
    "travel.outfit.y2k": "Y2K Pop",

    "travel.pose.natural": "Natural",
    "travel.pose.hugging": "Hugging",
    "travel.pose.jumping": "Jumping",
    "travel.pose.hand_in_hand": "Hand in Hand",
    "travel.pose.pointing": "Pointing",
    "travel.pose.looking_at_each_other": "Eye Contact",
    "travel.pose.peace_sign": "Peace Sign",
    "travel.pose.walking_away": "Walking Away",
    "travel.pose.sitting_relaxed": "Sitting Relaxed",
    "travel.pose.candid_laugh": "Candid Laugh",
    "travel.pose.leaning": "Leaning Posture",
    "travel.pose.coffee_time": "Coffee Time",
    "travel.pose.adjusting_shades": "Adjusting Shades",
    "travel.pose.cafe_sitting": "Cafe Relaxing",
    "travel.pose.photographer": "As Photographer",
    "travel.pose.heart": "Heart Gesture",

    "travel.label.relationship": "Relationship",
    "travel.relationship.default": "Default",
    "travel.relationship.couple": "Couple",
    "travel.relationship.family": "Family",
    "travel.relationship.friends": "Friends",
    "travel.relationship.siblings": "Siblings",
    "travel.relationship.parent_child": "Parent & Child",

    "travel.label.framing": "Camera Framing",
    "travel.framing.default": "Default",
    "travel.framing.closeup": "Close-up",
    "travel.framing.portrait": "Portrait",
    "travel.framing.full_body": "Full Body",
    "travel.framing.wide_angle": "Wide Angle",
    "travel.framing.aerial": "Aerial View",

    "travel.label.outfit_color": "Outfit Color",
    "travel.label.outfit_color_custom": "Custom Color",
    "travel.color.red": "Red",
    "travel.color.blue": "Blue",
    "travel.color.white": "White",
    "travel.color.black": "Black",
    "travel.color.beige": "Beige",
    "travel.color.pink": "Pink",
    "travel.color.green": "Green",
    "travel.color.yellow": "Yellow",

    "travel.label.clear_background": "Clear Background",
    "travel.clear_background.hint": "Remove other people from background",

    "travel.surprise_me": "Surprise Me!",
    "travel.surprise_me.hint": "Random scene, outfit, and pose",

    "travel.download": "Download",
    "travel.again": "Generate Another",
    "travel.edit_in_editor": "Edit in Editor",
    "travel.label.image_size": "Image Size",
    "travel.size_hint": "Flash: 1K only. Pro: 1K, 2K, 4K. Switch model in Settings.",
    "travel.size_1k": "1K",
    "travel.size_2k": "2K",
    "travel.size_4k": "4K",
    "travel.label.aspect_ratio": "Aspect Ratio",
    "travel.aspect_1_1": "1:1",
    "travel.aspect_16_9": "16:9",
    "travel.aspect_9_16": "9:16",
    "travel.label.style": "Photo Style",
    "travel.style.natural": "Natural",
    "travel.style.golden_hour": "Golden Hour",
    "travel.style.film": "Vintage Film",
    "travel.style.vibrant": "Vibrant",
    "travel.style.cinematic": "Cinematic",
    "travel.label.ref_image": "Reference Image",
    "travel.label.category": "Map Mode",
    "travel.category.scenery": "Scenery",
    "travel.category.food": "Gourmet",
    "travel.category.all": "All",
    "travel.ref_image.on": "On",
    "travel.ref_image.off": "Off",
    "travel.ref_image.hint": "Use real photo for realism",
    "travel.ref_image.upload": "Upload Custom Reference",
    "travel.ref_image.remove": "Remove",
    "travel.label.scene": "Scene",
    "travel.scene_hint": "Choose a preset or enter a custom scene (e.g. in Tokyo, city street, travel photography).",
    "travel.group.international": "International",
    "travel.group.taiwan": "Taiwan",
    "travel.region.north": "North Taiwan",
    "travel.region.central": "Central Taiwan",
    "travel.region.south": "South Taiwan",
    "travel.region.east": "East Taiwan",
    "travel.region.islands": "Offshore Islands",
    "travel.continent.europe": "Europe",
    "travel.continent.asia": "Asia",
    "travel.continent.namerica": "North America",
    "travel.continent.samerica": "South America",
    "travel.continent.oceania": "Oceania",
    "travel.continent.africa": "Africa",
    "travel.group.random": "Random",
    "travel.random_btn": "Random location",
    "travel.custom": "Custom",
    "travel.custom_btn": "Custom scene",
    "travel.custom_placeholder": "e.g. in Tokyo, city street, travel photography",
    "travel.custom_reference_label": "Reference scene photo",
    "travel.custom_reference_btn": "Choose image",
    "travel.custom_reference_remove": "Remove",
    "travel.error_no_image": "Please upload a portrait first.",
    "travel.error_no_scene": "Please select a scene or enter a custom description.",
    "travel.error_custom_scene_empty": "Please enter a description and/or upload a reference scene photo.",
    "travel.error_failed": "Travel photo generation failed.",
    "travel.map_mode_label": "Select Destination",
    "travel.map_world": "World",
    "travel.map_taiwan": "Taiwan",
    "travel.map_instruction": "Click on a marker to select the travel destination",
    "travel.status.analyzing": "Analyzing your portrait...",
    "travel.status.blending": "Blending with the world...",
    "travel.status.lighting": "Adjusting global lighting...",
    "travel.status.refining": "Refining fine details...",
    "travel.scene.shibuya": "Shibuya, Tokyo",
    "travel.scene.eiffel": "Eiffel Tower, Paris",
    "travel.scene.iceland": "Iceland",
    "travel.scene.santorini": "Santorini, Greece",
    "travel.scene.nyc": "Times Square, NYC",
    "travel.scene.london": "Big Ben, London",
    "travel.scene.rome": "Colosseum, Rome",
    "travel.scene.barcelona": "Sagrada Familia, Barcelona",
    "travel.scene.swiss_alps": "Swiss Alps",
    "travel.scene.neuschwanstein": "Neuschwanstein Castle",
    "travel.scene.pisa": "Leaning Tower of Pisa",
    "travel.scene.athens": "Acropolis of Athens",
    "travel.scene.moscow": "Red Square, Moscow",
    "travel.scene.taj_mahal": "Taj Mahal",
    "travel.scene.great_wall": "Great Wall of China",
    "travel.scene.mt_fuji": "Mount Fuji",
    "travel.scene.dubai": "Burj Khalifa, Dubai",
    "travel.scene.petra": "Petra, Jordan",
    "travel.scene.ankor_wat": "Angkor Wat",
    "travel.scene.bali": "Bali Rice Terrace",
    "travel.scene.seoul": "Seoul Tower",
    "travel.scene.singapore": "Marina Bay, Singapore",
    "travel.scene.grand_canyon": "Grand Canyon",
    "travel.scene.san_francisco": "Golden Gate Bridge",
    "travel.scene.banff": "Banff, Canada",
    "travel.scene.mexico": "Chichen Itza",
    "travel.scene.machu_picchu": "Machu Picchu",
    "travel.scene.rio": "Rio de Janeiro",
    "travel.scene.sydney": "Sydney Opera House",
    "travel.scene.nz": "New Zealand Landscape",
    "travel.scene.pyramids": "Pyramids of Giza",
    "travel.scene.cape_town": "Cape Town",
    "travel.scene.victoria_falls": "Victoria Falls",
    "travel.scene.serengeti": "Serengeti Safari",
    "travel.scene.venice": "Venice, Italy",
    "travel.scene.prague": "Prague Old Town",
    "travel.scene.amsterdam": "Amsterdam Canals",
    "travel.scene.cappadocia": "Cappadocia, Turkey",
    "travel.scene.kyoto": "Fushimi Inari, Kyoto",
    "travel.scene.halong_bay": "Ha Long Bay",
    "travel.scene.bangkok": "Wat Arun, Bangkok",
    "travel.scene.borobudur": "Borobudur Temple",
    "travel.scene.marrakesh": "Marrakesh Souks",
    "travel.scene.havana": "Old Havana, Cuba",
    "travel.scene.galapagos": "Galapagos Islands",
    "travel.scene.easter_island": "Easter Island",
    "travel.scene.iguazu": "Iguazu Falls",
    "travel.scene.uluru": "Uluru, Australia",
    "travel.scene.bora_bora": "Bora Bora",
    "travel.scene.everest": "Everest Base Camp",
    "travel.food.italy_pizza": "Neapolitan Pizza",
    "travel.food.france_croissant": "French Croissant",
    "travel.food.spain_paella": "Seafood Paella",
    "travel.food.germany_pretzel": "German Pretzel",
    "travel.food.uk_fishchips": "Fish and Chips",
    "travel.food.belgium_waffle": "Belgian Waffle",
    "travel.food.greece_gyro": "Greek Gyro",
    "travel.food.portugal_tart": "Egg Tart",
    "travel.food.switzerland_fondue": "Cheese Fondue",
    "travel.food.turkey_kebab": "Turkish Kebab",
    "travel.food.japan_sushi": "Japanese Sushi",
    "travel.food.japan_ramen": "Japanese Ramen",
    "travel.food.korea_bibimbap": "Korean Bibimbap",
    "travel.food.thailand_padthai": "Pad Thai",
    "travel.food.vietnam_pho": "Vietnamese Pho",
    "travel.food.india_curry": "Indian Curry",
    "travel.food.china_dimsum": "Dim Sum",
    "travel.food.singapore_crab": "Chili Crab",
    "travel.food.indonesia_satay": "Satay",
    "travel.food.malaysia_laksa": "Curry Laksa",
    "travel.food.philippines_adobo": "Chicken Adobo",
    "travel.food.usa_burger": "American Burger",
    "travel.food.usa_hotdog": "NY Hot Dog",
    "travel.food.mexico_tacos": "Mexican Tacos",
    "travel.food.canada_poutine": "Poutine",
    "travel.food.usa_bbq": "Texas BBQ",
    "travel.food.cuba_sandwich": "Cuban Sandwich",
    "travel.food.peru_ceviche": "Peruvian Ceviche",
    "travel.food.brazil_steak": "Brazilian Steak",
    "travel.food.argentina_empanada": "Empanada",
    "travel.food.chile_wine": "Chilean Red Wine",
    "travel.food.colombia_coffee": "Colombian Coffee",
    "travel.food.australia_meatpie": "Australian Meat Pie",
    "travel.food.australia_brunch": "Aussie Brunch",
    "travel.food.nz_lamb": "NZ Lamp",
    "travel.food.morocco_tagine": "Lamb Tagine",
    "travel.food.egypt_falafel": "Falafel",
    "travel.food.safrica_biltong": "Biltong",
    "travel.food.ethiopia_injera": "Injera",
    "travel.food.france_macaron": "Macaron",
    "travel.food.austria_sacher": "Sacher Torte",
    "travel.food.italy_gelato": "Italian Gelato",
    "travel.food.denmark_pastry": "Danish Pastry",
    "travel.food.baklava": "Baklava",
    "travel.food.hk_eggtart": "HK Egg Tart",
    "travel.food.russia_borscht": "Borscht",
    "travel.food.vietnam_coffee": "Vietnamese Coffee",
    "travel.food.japan_matcha": "Japanese Matcha",
    "travel.food.world_chocolate": "Artisanal Chocolate",
    // Taiwan North
    "travel.scene.taipei101": "Taipei 101",
    "travel.scene.jiufen": "Jiufen Old Street",
    "travel.scene.ximending": "Ximending",
    "travel.scene.cks_memorial": "CKS Memorial Hall",
    "travel.scene.raohe_market": "Raohe Night Market",
    "travel.scene.yehliu": "Yehliu Geopark",
    "travel.scene.shifen": "Shifen Waterfall",
    "travel.scene.tamsui": "Tamsui Fisherman's Wharf",
    "travel.scene.guiishan": "Guishan Island",
    // Taiwan Central
    "travel.scene.gaomei": "Gaomei Wetlands",
    "travel.scene.theater": "Taichung National Theater",
    "travel.scene.rainbow": "Rainbow Village",
    "travel.scene.sunmoonlake": "Sun Moon Lake",
    "travel.scene.qingjing": "Qingjing Farm",
    "travel.scene.hehuanshan": "Hehuanshan",
    "travel.scene.lugang": "Lugang Old Street",
    // Taiwan South
    "travel.scene.alishan": "Alishan",
    "travel.scene.hinoki": "Hinoki Village",
    "travel.scene.confucius": "Tainan Confucius Temple",
    "travel.scene.chimei": "Chimei Museum",
    "travel.scene.music_center": "Kaohsiung Music Center",
    "travel.scene.dragontiger": "Dragon and Tiger Pagodas",
    "travel.scene.dome": "Dome of Light",
    "travel.scene.kenting": "Kenting Beach",
    "travel.scene.eluanbi": "Eluanbi Lighthouse",
    // Taiwan East
    "travel.scene.taroko": "Taroko Gorge",
    "travel.scene.qingshui": "Qingshui Cliff",
    "travel.scene.mrbrown": "Mr. Brown Avenue",
    "travel.scene.sanxiantai": "Sanxiantai",
    // Taiwan Islands
    "travel.scene.penghu": "Penghu",
    "travel.food.boba": "Bubble Tea",
    "travel.food.beef_noodle": "Braised Beef Noodles",
    "travel.food.fried_chicken": "Fried Chicken Cutlet",
    "travel.food.xiaolongbao": "Soup Dumplings",
    "travel.food.shaved_ice": "Mango Shaved Ice",
    "travel.food.beef_soup": "Tainan Beef Soup",
    "travel.food.stinky_tofu": "Stinky Tofu",
    "travel.food.oyster_omelet": "Oyster Omelet",
    "travel.food.turkey_rice": "Chiayi Turkey Rice",
    "travel.food.braised_pork": "Braised Pork Rice",
    "travel.food.iron_egg": "Tamsui Iron Eggs",
    "travel.food.bawan": "Changhua Ba-wan",
    "travel.food.eel_noodle": "Tainan Eel Noodles",
    "travel.food.zongzi": "Sticky Rice Tamale",
    "travel.food.scallion_pancake": "Scallion Pancake",
    "travel.food.pineapple_cake": "Pineapple Cake",
    "travel.food.agei": "Tamsui A-gei",
    "travel.food.pig_blood": "Pig Blood Cake",
    "travel.food.danzai_noodle": "Danzai Noodles",
    "travel.food.coffin_bread": "Coffin Bread",
    "travel.food.boba.desc": "Taiwan's world-famous drink. Chewy tapioca pearls in creamy milk tea.",
    "travel.food.beef_noodle.desc": "Tender braised beef and chewy noodles in a rich, aromatic broth.",
    "travel.food.fried_chicken.desc": "Huge, crispy, and juicy fried chicken breast with special seasoning.",
    "travel.food.xiaolongbao.desc": "Delicate soup dumplings with thin skin and flavorful meat filling.",
    "travel.food.stinky_tofu.desc": "Fermented tofu deep-fried to perfection, served with pickled cabbage.",
    "travel.food.braised_pork.desc": "Comfort food featuring minced fatty pork over steaming white rice.",
    "travel.food.iron_egg.desc": "Chewy, dark-colored eggs slow-cooked in spices and air-dried.",
    "travel.food.scallion_pancake.desc": "Flaky, savory flatbread filled with fresh scallions and often egg.",
    "travel.food.pineapple_cake.desc": "Iconic buttery pastry with a sweet and tangy pineapple filling.",
    "travel.food.agei.desc": "Fried tofu filled with glass noodles, sealed with surimi.",
    "travel.food.pig_blood.desc": "Steamed sticky rice and pig blood cake with peanut powder.",
    "travel.food.bawan.desc": "Taiwanese meatball with a chewy translucent skin and pork filling.",
    "travel.food.oyster_omelet.desc": "Savory omelet with small oysters, starch, and sweet-spicy sauce.",
    "travel.food.shaved_ice.desc": "Refreshing dessert with mountains of ice and fresh seasonal fruits.",
    "travel.food.beef_soup.desc": "Fresh raw beef slices cooked instantly by hot clear broth.",
    "travel.food.turkey_rice.desc": "Shredded turkey over rice, drizzled with savory turkey drippings.",
    "travel.food.eel_noodle.desc": "Classic Tainan dish with sweet and sour sauce and crispy wok-fried eel.",
    "travel.food.zongzi.desc": "Sticky rice dumplings wrapped in bamboo leaves with various fillings.",
    "travel.food.danzai_noodle.desc": "Small bowl of noodles with minced pork, shrimp, and garlic.",
    "travel.food.coffin_bread.desc": "Thick fried toast hollowed out and filled with creamy seafood chowder.",
    "travel.food.italy_pizza.desc": "Authentic Neapolitan pizza with wood-fired crust and fresh local ingredients.",
    "travel.food.france_croissant.desc": "A flaky, buttery masterpiece from the heart of a Parisian bakery.",
    "travel.food.spain_paella.desc": "Vibrant saffron rice cooked with fresh seafood and traditional spices.",
    "travel.food.germany_pretzel.desc": "Giant salted pretzel, the perfect companion for a cold beer in Munich.",
    "travel.food.uk_fishchips.desc": "Classic British comfort food—crispy battered fish and thick-cut chips.",
    "travel.food.belgium_waffle.desc": "Sweet, crisp Brussels waffle topped with decadent fruits and chocolate.",
    "travel.food.greece_gyro.desc": "Savory grilled meat wrapped in warm pita with cool, creamy tzatziki.",
    "travel.food.portugal_tart.desc": "Lisbon's famous egg tart with a caramelized top and flaky pastry.",
    "travel.food.switzerland_fondue.desc": "Warm, melted Swiss cheese shared with friends in a cozy alpine chalet.",
    "travel.food.turkey_kebab.desc": "Spiced grilled meats steeped in centuries of Ottoman culinary tradition.",
    "travel.food.japan_sushi.desc": "Exquisite seasonal fish on vinegared rice—the pinnacle of Japanese craft.",
    "travel.food.japan_ramen.desc": "Hearty noodles in rich tonkotsu broth from the streets of Tokyo.",
    "travel.food.korea_bibimbap.desc": "A colorful, balanced bowl of rice, vegetables, and spicy gochujang.",
    "travel.food.thailand_padthai.desc": "The quintessential Thai street food—sweet, sour, and savory noodles.",
    "travel.food.vietnam_pho.desc": "Fragrant noodle soup that captures the bustling energy of Hanoi.",
    "travel.food.india_curry.desc": "A symphony of complex spices and tender meat, served with butter naan.",
    "travel.food.china_dimsum.desc": "Delicate bite-sized delights in bamboo steamers from South China.",
    "travel.food.singapore_crab.desc": "Sweet and spicy mud crab, a legendary delicacy in the Lion City.",
    "travel.food.usa_burger.desc": "The ultimate American classic—juicy beef, melted cheese, and a soft bun.",
    "travel.food.usa_hotdog.desc": "The iconic New York street snack—quick, simple, and full of character.",
    "travel.food.mexico_tacos.desc": "Fresh corn tortillas filled with vibrant, spicy, and authentic flavors.",

    "main.tab_retouch": "Retouch",
    "main.tab_adjust": "Adjust",
    "main.tab_filters": "Filters",
    "main.tab_crop": "Crop",
    "main.loading": "AI is working its magic...",
    "main.retouch_instr_initial": "Click an area on the image to make a precise edit.",
    "main.retouch_instr_ready": "Great! Now describe your localized edit below.",
    "main.retouch_placeholder_initial": "First click a point on the image",
    "main.retouch_placeholder_ready": "e.g., 'change my shirt color to blue'",
    "main.btn_generate": "Generate",
    "main.btn_undo": "Undo",
    "main.btn_redo": "Redo",
    "main.btn_compare": "Compare",
    "main.btn_reset": "Reset",
    "main.btn_start_over": "Start Over",
    "main.btn_download": "Download Image",

    "main.error_title": "An Error Occurred",
    "main.error_try_again": "Try Again",
    "main.error_no_image_edit": "No image loaded to edit.",
    "main.error_no_prompt_edit": "Please enter a description for your edit.",
    "main.error_no_hotspot": "Please click on the image to select an area to edit.",
    "main.error_failed_gen": "Failed to generate the image.",
    "main.error_no_image_filter": "No image loaded to apply a filter to.",
    "main.error_failed_filter": "Failed to apply the filter.",
    "main.error_no_image_adjust": "No image loaded to apply an adjustment to.",
    "main.error_failed_adjust": "Failed to apply the adjustment.",
    "main.error_no_crop": "Please select an area to crop.",
    "main.error_failed_crop": "Could not process the crop.",

    "panel.adjust.title": "Apply a Professional Adjustment",
    "panel.adjust.blur": "Blur Background",
    "panel.adjust.details": "Enhance Details",
    "panel.adjust.warm": "Warmer Lighting",
    "panel.adjust.studio": "Studio Light",
    "panel.adjust.placeholder": "Or describe an adjustment (e.g., 'change background to a forest')",
    "panel.adjust.apply": "Apply Adjustment",

    "panel.filter.title": "Apply a Filter",
    "panel.filter.synthwave": "Synthwave",
    "panel.filter.anime": "Anime",
    "panel.filter.lomo": "Lomo",
    "panel.filter.glitch": "Glitch",
    "panel.filter.placeholder": "Or describe a custom filter (e.g., '80s synthwave glow')",
    "panel.filter.apply": "Apply Filter",

    "panel.crop.title": "Crop Image",
    "panel.crop.instr": "Click and drag on the image to select a crop area.",
    "panel.crop.aspect": "Aspect Ratio:",
    "panel.crop.free": "Free",
    "panel.crop.id_2in_head": "2\" head 3.5×4.5",
    "panel.crop.id_2in_head_title": "ID, passport, Taiwan Travel Permit",
    "panel.crop.id_2in_half": "2\" half 4.2×4.7",
    "panel.crop.id_2in_half_title": "Health card, visa on arrival, int'l driver's license, resume, student ID",
    "panel.crop.id_1in": "1\" 2.8×3.5",
    "panel.crop.id_1in_title": "Driver's license, professional licenses, disability handbook",
    "panel.crop.apply": "Apply Crop",

    "settings.title": "Settings",
    "settings.model": "Model",
    "settings.model.flash": "Gemini Flash 2.5",
    "settings.model.pro": "Gemini 3 Pro",
    "settings.api_key": "API Key",
    "settings.api_key_placeholder": "Enter your Google GenAI API Key",
    "settings.api_key_desc": "Leave empty to use the default system key. Your key is stored locally.",
    "settings.save": "Save",
    "settings.cancel": "Cancel",
  },
  'zh-TW': {
    "app.title": "Pixshop",
    "common.none": "無",

    "start.title_part1": "AI 驅動的照片編輯器",
    "start.title_part2": "& 生成器",
    "start.subtitle": "上傳照片進行編輯，或描述您想要的內容讓 AI 為您生成。",
    "start.tab_upload": "上傳圖片",
    "start.tab_generate": "生成圖片",
    "start.upload_button": "上傳圖片",
    "start.upload_drag": "或拖放檔案至此",
    "start.select_image": "選擇一張圖片進行編輯",
    "start.edit_this": "編輯這張",
    "start.generate_new": "生成新圖片",
    "start.prompt_placeholder": "描述您想創建的圖片 (例如: '夜晚擁有霓虹燈的未來城市')",
    "start.aspect_ratio": "長寬比",
    "start.image_count": "圖片數量",
    "start.generate_button": "生成圖片",
    "start.generating": "生成中...",
    "start.generate_pro_slow_hint": "使用 Gemini 3 Pro 生成圖片可能需要 1～2 分鐘，請耐心等候。",
    "start.feature_retouch_title": "精準修圖",
    "start.feature_retouch_desc": "點擊圖片上的任意點以精確去除瑕疵、更改顏色或添加元素。",
    "start.feature_filter_title": "創意濾鏡",
    "start.feature_filter_desc": "用藝術風格轉換照片。從復古外觀到未來光輝，找到或創造完美的濾鏡。",
    "start.feature_adjust_title": "專業調整",
    "start.feature_adjust_desc": "增強光線、模糊背景或改變氛圍。無需複雜工具即可獲得工作室品質的結果。",
    "start.error_no_prompt": "請輸入圖片描述。",
    "start.error_gen_failed": "生成圖片失敗。",

    "start.tab_idphoto": "證件照",
    "start.tab_travel": "旅遊照",
    "start.idphoto_title": "AI 證件照",
    "start.idphoto_upload_hint": "上傳一張臉部清晰的正面肖像照",
    "start.idphoto_generate_btn": "生成證件照",
    "start.idphoto_generating": "證件照生成中…",
    "start.idphoto_download": "下載證件照",
    "start.idphoto_again": "再生成一張",
    "start.idphoto_edit": "進入編輯器",
    "start.idphoto_change_photo": "變更照片",
    "start.error_no_image_idphoto": "請先上傳一張肖像照。",
    "start.error_idphoto_failed": "證件照生成失敗。",

    "idphoto.label.type": "證件類型",
    "idphoto.label.level": "修圖等級",
    "idphoto.label.spec": "輸出規格",
    "idphoto.level.premium": "Premium 專業精修",
    "idphoto.level.standard": "Standard 自然標準",
    "idphoto.level.self": "SELF 原圖無修容",
    "idphoto.type.domestic": "國內證件",
    "idphoto.type.passport": "護照/簽證",
    "idphoto.type.taiwan_compatriot": "台胞證",
    "idphoto.type.student": "學生證",
    "idphoto.type.work": "工作證",
    "idphoto.type.military_police_medical": "軍警醫",
    "idphoto.type.cabin_crew": "空服員應試",
    "idphoto.type.graduation": "畢業照",
    "idphoto.spec.head_shoulders": "2吋大頭",
    "idphoto.spec.half_body": "2吋半身",
    "idphoto.label.clothing": "服裝",
    "idphoto.clothing.original": "原本衣服",
    "idphoto.clothing.scene_default": "場景預設衣服",
    "idphoto.clothing.business": "商務套裝",
    "idphoto.clothing.casual": "休閒家居服",
    "idphoto.clothing.graduation_gown": "學士服",
    "idphoto.clothing.suit": "西裝",
    "idphoto.clothing.custom": "使用者輸入自訂",
    "idphoto.clothing.custom_placeholder": "請描述想要的服裝（例如：白色襯衫、紅色領帶）",
    "idphoto.clothing.custom_image_label": "服裝參考圖（可選）",
    "idphoto.clothing.custom_image_btn": "選擇",
    "idphoto.clothing.custom_image_remove": "移除",
    "idphoto.error_custom_clothing_empty": "請輸入服裝描述或上傳參考圖。",
    "idphoto.model_recommendation": "推薦使用 Gemini 3 Pro 模型以獲得較佳的人物一致性，請在設定中切換。",
    "idphoto.result.params_title": "產生參數",

    "travel.title": "AI 旅遊照",
    "travel.upload_hint": "上傳一張臉部清楚的肖像照",
    "travel.change_photo": "變更照片",
    "travel.generate_btn": "生成旅遊照",
    "travel.generating": "旅遊照生成中…",
    "travel.result_scene_label": "場景：",

    "travel.weather.random": "隨機天氣",
    "travel.weather.sunny": "晴天",
    "travel.weather.rainy": "雨天",
    "travel.weather.snowy": "雪天",
    "travel.weather.cloudy": "多雲",
    "travel.weather.misty": "霧氣",

    "travel.time.random": "隨機時段",
    "travel.time.dawn": "清晨",
    "travel.time.noon": "正午",
    "travel.time.sunset": "落日",
    "travel.time.night": "深夜",

    "travel.vibe.zen": "禪意",
    "travel.vibe.retro": "復古",
    "travel.vibe.cyberpunk": "賽博龐克",
    "travel.vibe.street": "街拍",
    "travel.vibe.elegant": "優雅",
    "travel.vibe.adventure": "冒險",
    "travel.vibe.cozy": "溫馨",
    "travel.vibe.futuristic": "未來感",
    "travel.vibe.romantic": "浪漫",
    "travel.mode.single": "個人旅拍",
    "travel.mode.group": "多人合照",
    "travel.label.group_upload": "上傳人物照片 (最多 4 人)",
    "travel.error_no_images": "請至少挑選一張人物照片",
    "travel.status.group_analyzing": "正在分析多位成員特徵...",

    "travel.label.weather": "天氣氣候",
    "travel.label.time": "時間時段",
    "travel.label.vibe": "情緒濾鏡",
    "travel.label.vibe_desc": "根據地點為您推薦",
    "travel.label.outfit": "造型穿著",
    "travel.label.pose": "拍照動作",
    "travel.label.group_subject": "主角與互動設定",
    "travel.label.group_environment": "環境氣候設定",
    "travel.label.group_aesthetics": "藝術風格與氛圍",

    "travel.outfit.default": "場景預設",
    "travel.outfit.casual": "休閒服裝",
    "travel.outfit.formal": "各式正裝",
    "travel.outfit.traditional": "在地服飾",
    "travel.outfit.winter": "冬裝大衣",
    "travel.outfit.summer": "夏日清涼",
    "travel.outfit.hiking": "專業登山",
    "travel.outfit.cyberpunk": "機能特裝",
    "travel.outfit.luxury": "老錢風/靜奢",
    "travel.outfit.vintage": "經典復古",
    "travel.outfit.street_chic": "街頭時尚",
    "travel.outfit.preppy": "學院風格",
    "travel.outfit.boho": "波希米亞",
    "travel.outfit.parisian": "經典法式",
    "travel.outfit.academic": "暗黑學院",
    "travel.outfit.y2k": "千禧 Y2K",

    "travel.pose.natural": "自然站立",
    "travel.pose.hugging": "擁抱互動",
    "travel.pose.jumping": "開心跳躍",
    "travel.pose.hand_in_hand": "甜蜜牽手",
    "travel.pose.pointing": "指向景點",
    "travel.pose.looking_at_each_other": "對視微笑",
    "travel.pose.peace_sign": "耶！手勢",
    "travel.pose.walking_away": "背影漫步",
    "travel.pose.sitting_relaxed": "隨性坐姿",
    "travel.pose.candid_laugh": "自然大笑",
    "travel.pose.leaning": "帥氣倚靠",
    "travel.pose.coffee_time": "拿著咖啡",
    "travel.pose.adjusting_shades": "調整墨鏡",
    "travel.pose.cafe_sitting": "咖啡廳小憩",
    "travel.pose.photographer": "化身攝影師",
    "travel.pose.heart": "愛心手勢",

    "travel.label.relationship": "關係設定",
    "travel.relationship.default": "預設",
    "travel.relationship.couple": "情侶",
    "travel.relationship.family": "家人",
    "travel.relationship.friends": "好友",
    "travel.relationship.siblings": "兄弟姊妹",
    "travel.relationship.parent_child": "親子",

    "travel.label.framing": "鏡頭取景",
    "travel.framing.default": "預設",
    "travel.framing.closeup": "特寫",
    "travel.framing.portrait": "半身",
    "travel.framing.full_body": "全身",
    "travel.framing.wide_angle": "廣角",
    "travel.framing.aerial": "航拍",

    "travel.label.outfit_color": "服裝顏色",
    "travel.label.outfit_color_custom": "自訂顏色",
    "travel.color.red": "紅色",
    "travel.color.blue": "藍色",
    "travel.color.white": "白色",
    "travel.color.black": "黑色",
    "travel.color.beige": "米色",
    "travel.color.pink": "粉色",
    "travel.color.green": "綠色",
    "travel.color.yellow": "黃色",

    "travel.label.clear_background": "清場模式",
    "travel.clear_background.hint": "移除背景中的其他遊客",

    "travel.surprise_me": "驚喜隨機！",
    "travel.surprise_me.hint": "隨機場景、造型與動作",

    "travel.download": "下載",
    "travel.again": "再生成一張",
    "travel.edit_in_editor": "進入編輯器",
    "travel.label.image_size": "輸出尺寸",
    "travel.size_hint": "Flash 僅 1K；Pro 支援 1K、2K、4K。請在設定中切換模型。",
    "travel.size_1k": "1K",
    "travel.size_2k": "2K",
    "travel.size_4k": "4K",
    "travel.label.aspect_ratio": "輸出比例",
    "travel.aspect_1_1": "1:1",
    "travel.aspect_16_9": "16:9",
    "travel.aspect_9_16": "9:16",
    "travel.label.style": "照片風格",
    "travel.style.natural": "自然光",
    "travel.style.golden_hour": "黃金時刻",
    "travel.style.film": "復古底片",
    "travel.style.vibrant": "明亮鮮豔",
    "travel.style.cinematic": "電影質感",
    "travel.label.ref_image": "參考圖片",
    "travel.label.category": "顯示模式",
    "travel.category.scenery": "環境場景",
    "travel.category.food": "美食場景",
    "travel.category.all": "全部顯示",
    "travel.ref_image.on": "開啟",
    "travel.ref_image.off": "關閉",
    "travel.ref_image.hint": "若有真實照片則優先使用",
    "travel.ref_image.upload": "上傳自訂參考圖",
    "travel.ref_image.remove": "移除",
    "travel.label.scene": "場景",
    "travel.scene_hint": "選擇預設場景或輸入自訂描述（例如：in Tokyo, city street, travel photography）。",
    "travel.group.international": "國際",
    "travel.group.taiwan": "台灣環島",
    "travel.region.north": "北部地區",
    "travel.region.central": "中部地區",
    "travel.region.south": "南部地區",
    "travel.region.east": "東部地區",
    "travel.region.islands": "離島地區",
    "travel.continent.europe": "歐洲",
    "travel.continent.asia": "亞洲",
    "travel.continent.namerica": "北美洲",
    "travel.continent.samerica": "南美洲",
    "travel.continent.oceania": "大洋洲",
    "travel.continent.africa": "非洲",
    "travel.group.random": "隨機",
    "travel.random_btn": "隨機地點",
    "travel.custom": "自訂",
    "travel.custom_btn": "自訂場景",
    "travel.custom_placeholder": "例如：in Tokyo, city street, travel photography",
    "travel.custom_reference_label": "參考場景照片",
    "travel.custom_reference_btn": "選擇圖片",
    "travel.custom_reference_remove": "移除",
    "travel.error_no_image": "請先上傳一張肖像照。",
    "travel.error_no_scene": "請選擇場景或輸入自訂描述。",
    "travel.error_custom_scene_empty": "請輸入描述和／或上傳參考場景照片。",
    "travel.error_failed": "旅遊照生成失敗。",
    "travel.map_mode_label": "選擇景點",
    "travel.map_world": "世界地圖",
    "travel.map_taiwan": "台灣地圖",
    "travel.map_instruction": "點擊地圖上的標記來選擇旅遊地點",
    "travel.status.analyzing": "正在分析您的肖像...",
    "travel.status.blending": "正在融入異國場景...",
    "travel.status.lighting": "正在調整環境光影...",
    "travel.status.refining": "正在優化畫面細節...",
    "travel.scene.shibuya": "東京澀谷",
    "travel.scene.eiffel": "巴黎鐵塔",
    "travel.scene.iceland": "冰島",
    "travel.scene.santorini": "聖托里尼",
    "travel.scene.nyc": "紐約時報廣場",
    "travel.scene.london": "倫敦大笨鐘",
    "travel.scene.rome": "羅馬競技場",
    "travel.scene.barcelona": "巴塞隆納聖家堂",
    "travel.scene.swiss_alps": "瑞士阿爾卑斯山",
    "travel.scene.neuschwanstein": "德國新天鵝堡",
    "travel.scene.pisa": "比薩斜塔",
    "travel.scene.athens": "雅典衛城",
    "travel.scene.moscow": "莫斯科紅場",
    "travel.scene.taj_mahal": "泰姬瑪哈陵",
    "travel.scene.great_wall": "萬里長城",
    "travel.scene.mt_fuji": "富士山",
    "travel.scene.dubai": "杜拜哈里發塔",
    "travel.scene.petra": "約旦佩特拉",
    "travel.scene.ankor_wat": "吳哥窟",
    "travel.scene.bali": "峇里島梯田",
    "travel.scene.seoul": "首爾塔",
    "travel.scene.singapore": "新加坡濱海灣",
    "travel.scene.grand_canyon": "大峽谷",
    "travel.scene.san_francisco": "金門大橋",
    "travel.scene.banff": "加拿大班夫",
    "travel.scene.mexico": "墨西哥金字塔",
    "travel.scene.machu_picchu": "馬丘比丘",
    "travel.scene.rio": "里約熱內盧",
    "travel.scene.sydney": "雪梨歌劇院",
    "travel.scene.nz": "紐西蘭壯麗景觀",
    "travel.scene.pyramids": "埃及金字塔",
    "travel.scene.cape_town": "南非開普敦",
    "travel.scene.victoria_falls": "維多利亞瀑布",
    "travel.scene.serengeti": "塞倫蓋提獵遊",
    "travel.scene.venice": "威尼斯水都",
    "travel.scene.prague": "布拉格舊城",
    "travel.scene.amsterdam": "阿姆斯特丹運河",
    "travel.scene.cappadocia": "土耳其卡帕多奇亞",
    "travel.scene.kyoto": "京都伏見稻荷",
    "travel.scene.halong_bay": "下龍灣",
    "travel.scene.bangkok": "曼谷鄭王廟",
    "travel.scene.borobudur": "婆羅浮屠",
    "travel.scene.marrakesh": "馬拉喀什市集",
    "travel.scene.havana": "古巴哈瓦那",
    "travel.scene.galapagos": "加拉巴哥群島",
    "travel.scene.easter_island": "復活節島",
    "travel.scene.iguazu": "伊瓜蘇瀑布",
    "travel.scene.uluru": "澳洲艾爾斯岩",
    "travel.scene.bora_bora": "波拉波拉島",
    "travel.scene.everest": "聖母峰基地營",
    "travel.food.italy_pizza": "義大利披薩",
    "travel.food.france_croissant": "法國可頌",
    "travel.food.spain_paella": "西班牙海鮮燉飯",
    "travel.food.germany_pretzel": "德國扭結麵包",
    "travel.food.uk_fishchips": "英式炸魚薯條",
    "travel.food.belgium_waffle": "比利時鬆餅",
    "travel.food.greece_gyro": "希臘捲餅",
    "travel.food.portugal_tart": "葡式蛋塔",
    "travel.food.switzerland_fondue": "瑞士起司鍋",
    "travel.food.turkey_kebab": "土耳其烤肉",
    "travel.food.japan_sushi": "日本壽司",
    "travel.food.japan_ramen": "日本拉麵",
    "travel.food.korea_bibimbap": "韓式石鍋拌飯",
    "travel.food.thailand_padthai": "泰式炒河粉",
    "travel.food.vietnam_pho": "越南河粉",
    "travel.food.india_curry": "印度咖哩",
    "travel.food.china_dimsum": "港式點心",
    "travel.food.singapore_crab": "新加坡辣椒蟹",
    "travel.food.indonesia_satay": "印尼沙爹",
    "travel.food.malaysia_laksa": "馬來西亞叻沙",
    "travel.food.philippines_adobo": "菲律賓阿多波",
    "travel.food.usa_burger": "美式漢堡",
    "travel.food.usa_hotdog": "紐約熱狗",
    "travel.food.mexico_tacos": "墨西哥塔可",
    "travel.food.canada_poutine": "加拿大肉醬薯條",
    "travel.food.usa_bbq": "德州燒烤",
    "travel.food.cuba_sandwich": "古巴三明治",
    "travel.food.peru_ceviche": "秘魯醃魚",
    "travel.food.brazil_steak": "巴西窯烤",
    "travel.food.argentina_empanada": "阿根廷餡餅",
    "travel.food.chile_wine": "智利紅酒",
    "travel.food.colombia_coffee": "哥倫比亞咖啡",
    "travel.food.australia_meatpie": "澳洲肉派",
    "travel.food.australia_brunch": "澳式早午餐",
    "travel.food.nz_lamb": "紐西蘭烤羊排",
    "travel.food.morocco_tagine": "摩洛哥塔吉鍋",
    "travel.food.egypt_falafel": "埃及炸豆丸",
    "travel.food.safrica_biltong": "南非乾肉片",
    "travel.food.ethiopia_injera": "衣索比亞英傑拉",
    "travel.food.france_macaron": "法式馬卡龍",
    "travel.food.austria_sacher": "奧地利沙河蛋糕",
    "travel.food.italy_gelato": "義大利冰淇淋",
    "travel.food.denmark_pastry": "丹麥酥餅",
    "travel.food.baklava": "中東帕克拉瓦",
    "travel.food.hk_eggtart": "港式蛋塔",
    "travel.food.russia_borscht": "羅宋湯",
    "travel.food.vietnam_coffee": "越南咖啡",
    "travel.food.japan_matcha": "日本抹茶",
    "travel.food.world_chocolate": "精品巧克力",
    // Taiwan North
    "travel.scene.taipei101": "台北 101",
    "travel.scene.jiufen": "九份老街",
    "travel.scene.ximending": "西門町",
    "travel.scene.cks_memorial": "中正紀念堂",
    "travel.scene.raohe_market": "饒河夜市",
    "travel.scene.yehliu": "野柳女王頭",
    "travel.scene.shifen": "十分瀑布",
    "travel.scene.tamsui": "淡水漁人碼頭",
    "travel.scene.guiishan": "龜山島",
    // Taiwan Central
    "travel.scene.gaomei": "高美濕地",
    "travel.scene.theater": "台中國家歌劇院",
    "travel.scene.rainbow": "彩虹眷村",
    "travel.scene.sunmoonlake": "日月潭",
    "travel.scene.qingjing": "清境農場",
    "travel.scene.hehuanshan": "合歡山",
    "travel.scene.lugang": "鹿港老街",
    // Taiwan South
    "travel.scene.alishan": "阿里山",
    "travel.scene.hinoki": "檜意森活村",
    "travel.scene.confucius": "台南孔廟",
    "travel.scene.chimei": "奇美博物館",
    "travel.scene.music_center": "高雄流行音樂中心",
    "travel.scene.dragontiger": "龍虎塔",
    "travel.scene.dome": "美麗島光之穹頂",
    "travel.scene.kenting": "墾丁白沙灣",
    "travel.scene.eluanbi": "鵝鑾鼻燈塔",
    // Taiwan East
    "travel.scene.taroko": "太魯閣峽谷",
    "travel.scene.qingshui": "清水斷崖",
    "travel.scene.mrbrown": "伯朗大道",
    "travel.scene.sanxiantai": "三仙台",
    // Taiwan Islands
    "travel.scene.penghu": "澎湖",
    "travel.food.boba": "珍珠奶茶",
    "travel.food.beef_noodle": "紅燒牛肉麵",
    "travel.food.fried_chicken": "大雞排",
    "travel.food.xiaolongbao": "小籠包",
    "travel.food.shaved_ice": "芒果冰",
    "travel.food.beef_soup": "台南牛肉湯",
    "travel.food.stinky_tofu": "炸臭豆腐",
    "travel.food.oyster_omelet": "蚵仔煎",
    "travel.food.turkey_rice": "嘉義火雞肉飯",
    "travel.food.braised_pork": "滷肉飯",
    "travel.food.iron_egg": "淡水鐵蛋",
    "travel.food.bawan": "彰化肉圓",
    "travel.food.eel_noodle": "台南鱔魚意麵",
    "travel.food.zongzi": "肉粽",
    "travel.food.scallion_pancake": "蔥油餅",
    "travel.food.pineapple_cake": "鳳梨酥",
    "travel.food.agei": "淡水阿給",
    "travel.food.pig_blood": "豬血糕",
    "travel.food.danzai_noodle": "台南擔仔麵",
    "travel.food.coffin_bread": "棺材板",
    "travel.food.boba.desc": "台灣揚名國際的飲品，Q彈珍珠搭配香醇奶茶。",
    "travel.food.beef_noodle.desc": "軟嫩紅燒牛肉搭配香Q麵條，與層次豐富的濃醇湯頭。",
    "travel.food.fried_chicken.desc": "超大片、外酥內嫩的黃金雞排，灑上特色椒鹽粉。",
    "travel.food.xiaolongbao.desc": "皮薄透光、湯汁豐富的精緻小籠湯包。",
    "travel.food.stinky_tofu.desc": "聞起來臭、吃起來香的酥炸豆腐，配上爽口台式泡菜。",
    "travel.food.braised_pork.desc": "台灣人的靈魂美食，鹹香誘人的滷肉澆淋在白飯上。",
    "travel.food.iron_egg.desc": "淡水特色名產，口感Q彈有嚼勁的黑色小蛋。",
    "travel.food.scallion_pancake.desc": "層次分明、充滿蔥香的酥脆餅皮。",
    "travel.food.pineapple_cake.desc": "經典伴手禮，酥鬆外皮包裹著甜而不膩的鳳梨餡。",
    "travel.food.agei.desc": "淡水獨特小吃，油豆腐內塞滿冬粉再用魚漿封口。",
    "travel.food.pig_blood.desc": "傳統古早味，沾滿花生粉與香菜的Q彈豬血糕。",
    "travel.food.bawan.desc": "彰化特色肉圓，Q彈外皮包裹著紮實肉餡與筍丁。",
    "travel.food.oyster_omelet.desc": "鮮甜蚵仔搭配特製粉漿、雞蛋與甜辣醬汁。",
    "travel.food.shaved_ice.desc": "消暑聖品，堆疊如山的剉冰加上滿滿的新鮮芒果。",
    "travel.food.beef_soup.desc": "台南人的早餐，鮮甜溫體牛淋上滾燙清湯。",
    "travel.food.turkey_rice.desc": "嘉義名產，滑嫩火雞肉絲淋上香噴噴的雞油。",
    "travel.food.eel_noodle.desc": "台南經典小吃，酸甜適中的醬汁與大火爆炒的爽脆鱔魚。",
    "travel.food.zongzi.desc": "竹葉包裹著香噴噴的糯米，內餡豐富入味。",
    "travel.food.danzai_noodle.desc": "精緻小碗麵食，淋上特製滷肉燥與鮮甜蝦頭湯。",
    "travel.food.coffin_bread.desc": "油炸後的厚片土司挖空，裝入濃郁的海鮮濃湯內餡。",
    "travel.food.italy_pizza.desc": "道地的拿坡里噴香披薩，口感焦脆、起司濃郁。",
    "travel.food.france_croissant.desc": "巴黎街頭最具代表性的奶油酥皮精品。",
    "travel.food.spain_paella.desc": "鮮豔奪目的番紅花燉飯，滿載地中海的鮮甜海味。",
    "travel.food.germany_pretzel.desc": "慕尼黑啤酒節的最佳拍檔，巨大的鹹香蝴蝶圈。",
    "travel.food.uk_fishchips.desc": "最具英倫風情的平民美食——酥炸鮮魚與粗薯條。",
    "travel.food.belgium_waffle.desc": "格紋細緻的比利時鬆餅，淋上滿滿的巧克力醬。",
    "travel.food.greece_gyro.desc": "希臘街頭常見的餅捲烤肉，搭配沁涼清爽的優格醬。",
    "travel.food.portugal_tart.desc": "里斯本著名的葡式蛋塔，焦糖表面與層層酥皮。",
    "travel.food.switzerland_fondue.desc": "在阿爾卑斯山的小木屋裡，與好友分享溫暖的熔岩起司。",
    "travel.food.turkey_kebab.desc": "傳承百年的鄂圖曼火烤美味，香料醃漬的紮實肉質。",
    "travel.food.japan_sushi.desc": "依循季節嚴選的旬鮮食材，指尖上的職人工藝。",
    "travel.food.japan_ramen.desc": "濃縮職人魂的豚骨湯頭，搭配Q彈麵條與誘人叉燒。",
    "travel.food.korea_bibimbap.desc": "五顏六色的蔬菜與特製辣醬，拌出韓國的經典養生味。",
    "travel.food.thailand_padthai.desc": "泰國街頭不可或缺的國民美食——酸、甜、辣的完美結合。",
    "travel.food.vietnam_pho.desc": "清爽卻不失深度的高湯掛勾著河粉，濃縮河內的晨間氣息。",
    "travel.food.india_curry.desc": "辛香料交織的複雜層次，搭配熱騰騰的高級奶油烤餅。",
    "travel.food.china_dimsum.desc": "南中國傳統茶樓文化中，最精緻講究的玲瓏點心。",
    "travel.food.singapore_crab.desc": "獅城傳奇名餚，甜辣適中的巨型青蟹與酥香饅頭。",
    "travel.food.usa_burger.desc": "美式文化的終極體現——多汁牛肉、熔岩起司與鬆軟麵包。",
    "travel.food.usa_hotdog.desc": "紐約時代廣場最經典的街頭速食，快速簡單卻充滿活力。",
    "travel.food.mexico_tacos.desc": "新鮮玉米餅皮包裹各種辛辣鮮甜的在地滋味。",

    "main.tab_retouch": "修圖",
    "main.tab_adjust": "調整",
    "main.tab_filters": "濾鏡",
    "main.tab_crop": "裁切",
    "main.loading": "AI 正在施展魔法...",
    "main.retouch_instr_initial": "點擊圖片上的區域進行精確編輯。",
    "main.retouch_instr_ready": "太棒了！現在在下方描述您的編輯需求。",
    "main.retouch_placeholder_initial": "請先點擊圖片上的一點",
    "main.retouch_placeholder_ready": "例如: '將我的襯衫顏色改為藍色'",
    "main.btn_generate": "生成",
    "main.btn_undo": "復原",
    "main.btn_redo": "重做",
    "main.btn_compare": "比較",
    "main.btn_reset": "重置",
    "main.btn_start_over": "重新開始",
    "main.btn_download": "下載圖片",

    "main.error_title": "發生錯誤",
    "main.error_try_again": "重試",
    "main.error_no_image_edit": "未載入圖片。",
    "main.error_no_prompt_edit": "請輸入編輯描述。",
    "main.error_no_hotspot": "請點擊圖片選擇要編輯的區域。",
    "main.error_failed_gen": "生成圖片失敗。",
    "main.error_no_image_filter": "未載入圖片。",
    "main.error_failed_filter": "應用濾鏡失敗。",
    "main.error_no_image_adjust": "未載入圖片。",
    "main.error_failed_adjust": "應用調整失敗。",
    "main.error_no_crop": "請選擇裁切區域。",
    "main.error_failed_crop": "無法執行裁切。",

    "panel.adjust.title": "應用專業調整",
    "panel.adjust.blur": "模糊背景",
    "panel.adjust.details": "增強細節",
    "panel.adjust.warm": "溫暖光線",
    "panel.adjust.studio": "攝影棚光",
    "panel.adjust.placeholder": "或描述調整內容 (例如: '將背景改為森林')",
    "panel.adjust.apply": "應用調整",

    "panel.filter.title": "應用濾鏡",
    "panel.filter.synthwave": "合成波",
    "panel.filter.anime": "動漫",
    "panel.filter.lomo": "Lomo",
    "panel.filter.glitch": "故障風",
    "panel.filter.placeholder": "或描述自定義濾鏡 (例如: '80年代合成波光輝')",
    "panel.filter.apply": "應用濾鏡",

    "panel.crop.title": "裁切圖片",
    "panel.crop.instr": "在圖片上點擊並拖動以選擇裁切區域。",
    "panel.crop.aspect": "長寬比:",
    "panel.crop.free": "自由",
    "panel.crop.id_2in_head": "2吋大頭 3.5×4.5",
    "panel.crop.id_2in_head_title": "身分證 / 護照 / 台胞證",
    "panel.crop.id_2in_half": "2吋半身 4.2×4.7",
    "panel.crop.id_2in_half_title": "健保卡 / 落地簽證 / 國際駕照 / 履歷照 / 學生證",
    "panel.crop.id_1in": "1吋 2.8×3.5",
    "panel.crop.id_1in_title": "駕照 / 執照證照 / 身心障礙手冊",
    "panel.crop.apply": "應用裁切",

    "settings.title": "設定",
    "settings.model": "模型",
    "settings.model.flash": "Gemini Flash 2.5",
    "settings.model.pro": "Gemini 3 Pro",
    "settings.api_key": "API 金鑰",
    "settings.api_key_placeholder": "輸入您的 Google GenAI API Key",
    "settings.api_key_desc": "留空則使用系統預設金鑰。您的金鑰僅儲存在本地。",
    "settings.save": "儲存",
    "settings.cancel": "取消",
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
